### ISSUE TITLE
game crashes when query with too many bind parameters is getting executed

### ISSUE THREAD

**Issue by Fusselwurm** [intercept/intercept-database#9]
example:

from the config

```yaml
# ...
accounts:
    foo: 
# ...

statements:
    foostmt: "select 1"
# ...
```

```sqf 
private _connection = dbCreateConnection "foo";
private _query = dbPrepareQueryConfig  ["foostmt", ["foo"]]; 
private _result = _connection dbExecute _query; // crash to desktop
```
